/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActividadesRouteImport } from './routes/_authenticated/actividades'
import { Route as AuthenticatedEstadisticasRouteImport } from './routes/_authenticated/estadisticas'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActividadesRoute =
  AuthenticatedActividadesRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstadisticasRoute =
  AuthenticatedEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/actividades': typeof AuthenticatedActividadesRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/actividades': typeof AuthenticatedActividadesRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/actividades': typeof AuthenticatedActividadesRoute
  '/_authenticated/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/actividades' | '/estadisticas' | '/sesiones' | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/actividades' | '/estadisticas' | '/sesiones' | '/auth/callback' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/actividades'
    | '/_authenticated/estadisticas'
    | '/_authenticated/sesiones'
    | '/auth/callback'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actividades': {
      id: '/_authenticated/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof AuthenticatedActividadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estadisticas': {
      id: '/_authenticated/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AuthenticatedEstadisticasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActividadesRoute: typeof AuthenticatedActividadesRoute
  AuthenticatedEstadisticasRoute: typeof AuthenticatedEstadisticasRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActividadesRoute: AuthenticatedActividadesRoute,
  AuthenticatedEstadisticasRoute: AuthenticatedEstadisticasRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
